# Generated by Django 3.0 on 2023-10-11 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mydatabase',
            new_name='userinfo',
        ),
    ]
